# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-19 12:18
from __future__ import unicode_literals

from django.db import migrations, models
import embed_video.fields


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
                ('video', embed_video.fields.EmbedVideoField()),
            ],
        ),
    ]
