# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-22 19:41
from __future__ import unicode_literals

from django.db import migrations
import markdownx.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_article'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='text',
            field=markdownx.models.MarkdownxField(default=''),
        ),
    ]
