# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-28 10:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20180428_1211'),
    ]

    operations = [
        migrations.AddField(
            model_name='spotlight',
            name='created',
            field=models.DateTimeField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name='spotlight',
            name='edited',
            field=models.DateTimeField(null=True),
        ),
    ]
