# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-28 14:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20180428_1514'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='spotlight',
            name='left',
        ),
        migrations.RemoveField(
            model_name='spotlight',
            name='right',
        ),
        migrations.AddField(
            model_name='spotlight',
            name='left_image',
            field=models.URLField(default='http://cdn7.bigcommerce.com/s-viqdwewl26/stencil/8f903ed0-76e7-0135-12e4-525400970412/icons/icon-no-image.svg'),
        ),
        migrations.AddField(
            model_name='spotlight',
            name='left_url',
            field=models.URLField(default='/'),
        ),
        migrations.AddField(
            model_name='spotlight',
            name='right_image',
            field=models.URLField(default='http://cdn7.bigcommerce.com/s-viqdwewl26/stencil/8f903ed0-76e7-0135-12e4-525400970412/icons/icon-no-image.svg'),
        ),
        migrations.AddField(
            model_name='spotlight',
            name='right_url',
            field=models.URLField(default='/'),
        ),
        migrations.AlterField(
            model_name='spotlight',
            name='left_title',
            field=models.CharField(default='', max_length=24),
        ),
        migrations.AlterField(
            model_name='spotlight',
            name='right_title',
            field=models.CharField(default='', max_length=24),
        ),
    ]
