# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-23 18:44
from __future__ import unicode_literals

from django.db import migrations
import embed_video.fields


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_article_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='video',
            field=embed_video.fields.EmbedVideoField(blank=True, null=True),
        ),
    ]
