# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-30 12:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20180430_1340'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='image',
            field=models.URLField(default='http://cdn7.bigcommerce.com/s-viqdwewl26/stencil/8f903ed0-76e7-0135-12e4-525400970412/icons/icon-no-image.svg'),
        ),
    ]
