# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-30 11:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usermanagement', '0002_members'),
    ]

    operations = [
        migrations.AddField(
            model_name='members',
            name='functie',
            field=models.CharField(default='', max_length=128),
        ),
    ]
