# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-30 11:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import markdownx.models


class Migration(migrations.Migration):

    dependencies = [
        ('usermanagement', '0003_members_functie'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('biography', markdownx.models.MarkdownxField()),
            ],
        ),
        migrations.AddField(
            model_name='members',
            name='contact',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='members', to='usermanagement.Contact'),
        ),
    ]
