# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-30 11:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usermanagement', '0004_auto_20180430_1343'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='created',
            field=models.DateField(blank=True, null=True),
        ),
    ]
